apiVersion: demo.kubecon2025na.io/v1
kind: Database
metadata:
  annotations:
    terasky.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=vrabbi-demo&repo=demo-gitops","gitLayout":"cluster-scoped","basePath":"demo-cluster/backstack-demo/Database"}
    terasky.backstage.io/add-to-catalog: 'true'
    terasky.backstage.io/owner: group:default/guests
    terasky.backstage.io/system: backstack-demo
    terasky.backstage.io/source-file-url: >-
      https://github.com/vrabbi-demo/demo-gitops/blob/main/demo-cluster/backstack-demo/Database/db-test-01.yaml
  name: db-test-01
  namespace: backstack-demo
spec:
  highAvailability: false
  storageGB: 1
  version: 17.1
